version: "3.7"
services:
    memcached:
        image: memcached:1.6-alpine
        container_name: cropofil-memcached
        networks:
            - default
        labels:
            - "traefik.enable=false"

    redis:
        image: redis:6.0-alpine
        container_name: cropofil-redis
        networks:
            - default
        labels:
            - "traefik.enable=false"

    nodejs:
        image: node:14.3-alpine
        container_name: cropofil-nodejs
        tty: true
        stdin_open: true
        working_dir: /application
        volumes:
            - .:/application
        networks:
            - default
        labels:
            - "traefik.enable=false"

    postgres:
        image: postgres:11.1-alpine
        container_name: cropofil-postgres
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=cropofil
        ports:
            - "7074:5432"
        networks:
            - default
        labels:
            - "traefik.enable=false"

    webserver:
        image: nginx:1.17-alpine
        container_name: cropofil-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        #ports:
        #    - "7070:80"
        labels:
            - "traefik.http.routers.webserver-cropofil.rule=Host(`cropofil.localhost`)"
            - "traefik.http.services.webserver-cropofil.loadbalancer.server.port=80"
        networks:
            - vps-traefik
            - default

    php-fpm:
        build: phpdocker/php-fpm
        container_name: cropofil-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        networks:
            - default
        labels:
            - "traefik.enable=false"

networks:
    default:
    vps-traefik:
        external: true